# This file is a template, and might need editing before it works on your project.
docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$(date +'%Y%m%d') || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$(date +'%Y%m%d') --tag $CI_REGISTRY_IMAGE:$(date +'%Y%m%d') .
    - docker push $CI_REGISTRY_IMAGE:$(date +'%Y%m%d')

docker-test:
  # Official docker image.
  image: docker/compose:latest
  stage: test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "$CI_REGISTRY_IMAGE:$(date +'%Y%m%d')"
  script:
    - sed -i "s/magento2:latest/magento2:$(date +'%Y%m%d')/" docker-compose.yml
    - echo "$CI_REGISTRY_IMAGE:$(date +'%Y%m%d')"
    - cat docker-compose.yml
    - docker-compose up --no-build --quiet-pull -d 
    - docker-compose logs -f magento mariadb | while read LOGLINE; do echo "${LOGLINE}"; [[ "${LOGLINE}" == *"Starting magento..."* ]] && pkill -P $$ docker-compose; done
    - docker tag "$CI_REGISTRY_IMAGE:$(date +'%Y%m%d')" "$CI_REGISTRY_IMAGE:latest",
    - docker push "$CI_REGISTRY_IMAGE:latest"
