version: '3.7'
services:
  mariadb:
    image: 'bitnami/mariadb'
    env_file:
      - .env
    volumes:
      - './data/mariadb:/bitnami/mariadb'
  magento:
    build:
      context: .
      dockerfile: sampledata/Dockerfile
    image: 'registry.gitlab.com/gbitdev/magento2:latest-sampledata'
    env_file:
      - .env
    environment:
      - THEME=Alpaca
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
