version: '3.7'
services:
  varnish:
    image: 'webdevops/varnish'
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/varnish:/opt/docker/etc/varnish
    depends_on:
      - magento
  redis:
    image: 'bitnami/redis:5.0'
    env_file:
      - .env
    volumes:
      - 'redis_data:/bitnami/redis/data'
  mariadb:
    image: 'bitnami/mariadb'
    env_file:
      - .env
    volumes:
      - './data/mariadb:/bitnami/mariadb'
  magento:
    image: 'registry.gitlab.com/gbitdev-magento2/magento2-docker/magento:latest'
    build:
      context: .
      args:
        - THEME=
    env_file:
      - .env
    volumes:
      # - './bin/upgrade.sh:/opt/bitnami/magento/htdocs/bin/upgrade.sh'
      - './data/magento:/bitnami/magento'
      - './data/varnish:/bitnami/varnish'
      # - 'apache_logs:/opt/bitnami/apache/logs'
    depends_on:
      - mariadb
      - redis
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  # goaccess:
  #   image: 'allinurl/goaccess'
  #   ports:
  #     - 7890:7890
  #   volumes:
  #     - goaccess_data:/srv/data
  #     - goaccess_html:/srv/report
  #     - apache_logs:/srv/logs
volumes:
  redis_data:
  # apache_logs:
  # goaccess_data:
  # goaccess_html:
