version: '2'
services:
  magento:
    image: 'registry.gitlab.com/gbitdev/magento2:2.4.0'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=admin
      - MAGENTO_DATABASE_PASSWORD=nimda123
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - REDIS_HOST=redis
      - REDIS_PORT_NUMBER=6379
      - MAGENTO_HOST=magento.local
      - PHP_MEMORY_LIMIT='-1'
      - NAMI_DEBUG=TRUE
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'magento_data:/bitnami'
volumes:
  magento_data:
    driver: local
